### ISSUE TITLE
zooniverse-logo provided with height/width constrained

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Zooniverse-React-Components#24]
I think the zooniverse-logo CSS, specifically https://github.com/zooniverse/Zooniverse-React-Components/blob/master/src/css/zooniverse-logo.styl#L3 is constricting the sizing when height and width is provided as props to the component, like in https://github.com/zooniverse/Zooniverse-React-Components/blob/master/src/css/zooniverse-logo.styl#L3. As shown at https://lab-preview.zooniverse.org/.

I'll add tests and try removing width (and arguably top?) from ZRC component CSS to zooniverse-logo and zooniverse-logotype and report back.

**Comment by srallen** [comment]
Fixed in #25
