### ISSUE TITLE
DisplayNameSlugEditor accept custom origin property

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Zooniverse-React-Components#28]
update DisplayNameSlugEditor component to accept `origin` property so if something like `origin="https://www.zooniverse.org"` provided the explanation text would include "Your organization's URL is https://www.zooniverse.org/[type]/[slug]...".

**Comment by srallen** [comment]
Looks like the origin is a prop already: https://github.com/zooniverse/Zooniverse-React-Components/blob/master/src/components/display-name-slug-editor.jsx#L122

This is a good reminder that we need to add docs for the components that are present. I'd welcome some help with this.

**Comment by mcbouslog** [comment]
Ok sorry should have seen this originally - I think [this line](https://github.com/zooniverse/Zooniverse-React-Components/blob/master/src/components/display-name-slug-editor.jsx#L98) just needs to be changed to:
`{this.props.origin + state.url}`
(similar to the `href`)?

**Comment by mcbouslog** [comment]
wait and the href might need editing, posted too soon, working on it...
