### ISSUE TITLE
Fix outdated dependencies

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Zooniverse-React-Components#70]
There are a few dependencies with moderate severity that should be updated. They include:

- `braces`: should be upgraded to at least `2.3.1`
- `acorn`: should be upgraded to at least `6.4.1`
- `minimist`: should be upgraded to at least `0.2.1`

Alternatively, `npm audit fix` may upgrade these dependencies without breaking anything.

**Comment by mcbouslog** [comment]
Upgrading to node version 8.17.0 (last of v8) and regenerating the `package-lock.json` appears to fix `acorn`, `minimist`, and many other issues noted in an `npm audit`, though I know not the ideal approach (regenerating `package-lock.json`--) without issue here (ZRC) or in apps that depend on ZRC.

The `braces` upgrade I believe will require upgrading `babel` to v7, which shouldn't be bad, but thought could be different PR.

I'm npm linking to `pfe-lab` and `notes-from-nature-field-book` for testing. To determine if changes here (ZRC) break anything, `pfe-lab` could use a little maintenance I'll try to include shortly as well.
