### ISSUE TITLE
Bump ZRC to v0.9.3

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Zooniverse-React-Components#90]
Per a few recent security updates and related maintenance, time for a version bump.

I think the order of events should be:

- [x] 1. merge related open PRs
- [x] 2. test on repos that have ZRC as dependency (`npm link` running locally)
- [x] 3. PR to update CHANGELOG and bump version
- [x] 4. update repos that have ZRC as dependency
  - [x] NfN Field Book
  - [x] pfe-lab
  - [x] scribes
  - [x] ASM
  - [x] edu-API-front-end

I think the following list comprises active code/repos using ZRC that'll need updating:

 https://github.com/zooniverse/pfe-lab
 https://github.com/zooniverse/scribes-of-the-cairo-geniza
 https://github.com/zooniverse/anti-slavery-manuscripts
 https://github.com/zooniverse/edu-api-front-end
 https://github.com/zooniverse/notes-from-nature-field-book

**Comment by shaunanoordin** [comment]
List of relevant PRs:
- NfN Field Book : TODO
- pfe-lab : TODO
- scribes : TODO
- ASM: TODO
- classroom/edu-api-front-end : https://github.com/zooniverse/classroom/pull/253

(This post will be updated)
